- name: Declare Variable
  hosts: all
  vars:
    URL: example.com
  tasks:
    - name: Print the URL variable
      ansible.builtin.debug:
        msg: URL - {{ URL }}







#In shell we are using ${} to delare variable
#In ansible we use 2 curly braces to declare the variable